AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Auto Scaling Group in private subnet with ALB-accessible security group

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for EC2 (custom or from AWS catalog)
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

Resources:

  # EC2 Security Group allowing HTTP access from ALB's SG
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 allowing ALB access
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !ImportValue AlbSecurityGroupId
      Tags:
        - Key: Name
          Value: EC2-SG

  # Launch Template for EC2 instances
  WebServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId: !ImportValue PrivateSubnetId
            AssociatePublicIpAddress: false
            Groups:
              - !Ref EC2SecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: WebServer

  # Auto Scaling Group to manage EC2 instances
  WebServerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue PrivateSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref WebServerLaunchTemplate
        Version: !GetAtt WebServerLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - !ImportValue AlbTargetGroupArn
      Tags:
        - Key: Name
          Value: WebServer
          PropagateAtLaunch: true
